### ISSUE TITLE
Documentation request: Row and column selection and iteration examples

### ISSUE THREAD

**Issue by jorvis** [theislab/anndata#11]
I've found that I can select multiple rows and then iterate over their columns and values like this:

```
# Trying to find how to get one gene
selected = adata[:, adata.var_names.isin(['Tcea1', 'Xkr4'])]  # works

# this version only works if I'm using a sparse matrix, if not the tocoo() call fails.
#cx = adata.X.tocoo()    
#for cell, gene, value in zip(adata.obs_names[cx.row], adata.var_names[cx.col], cx.data):
#    print(cell, gene, value)

# This is for a complete matrix
for g, gene in enumerate(selected.var_names):
    for c, cell in enumerate(selected.obs_names):
        print("{0}\t{1}\t{2}".format(cell, gene, selected.X[c, g]))
```

But now I want to select just ONE row and iterate over its columns and values.  

These do not work.  

```
selected = adata[:, adata.var_names.isin(['Tcea1',])] # this doesn't
selected = adata[:, adata.var_names['Tcea1']]  # this doesn't
``
What actually fails each time though isn't getting selected, it's trying to print it:

```
Traceback (most recent call last):
  File "./h5ad_test_read.py", line 35, in <module>
    print("{0}\t{1}\t{2}".format(cell, gene, selected.X[c, g]))
IndexError: too many indices for array
```

I'd love to see an example of doing this correctly for a single gene.

**Comment by jorvis** [comment]
Of course, asking for help is often the fastest way to find the answer on your own.  This works:

```
selected = adata[:, adata.var_names.isin(['Tcea1',])]

# This is for a complete matrix
for g, gene in enumerate(selected.var_names):
    for c, cell in enumerate(selected.obs_names):
        print("{0}\t{1}\t{2}".format(cell, gene, selected.X[c]))
```

It seems like using "isin()" when you're only going after one gene is suboptimal though.

**Comment by falexwolf** [comment]
Hi Joshua!
When you select one row or column, the matrix will get flattened, as this is numpy's behavior and often very practical. See the following comment in the `Notes` section http://anndata.readthedocs.io/en/latest/anndata.AnnData.html
```
adata = AnnData(np.ones((2, 2)))
adata[:, 0].X == adata.X[:, 0]
```
So, if you're only going for single gene, then you get a 1d vector and not a matrix. Would you like to see this behavior different? Your trick with `['Tcea1', ]` is definitely a very good workaround if you want something two-dimensional.

PS: You can also use `'Tcea1' == adata.var_names` instead of using `.isin(...)` when you only have a single element.

**Comment by flying-sheep** [comment]
> Of course, asking for help is often the fastest way to find the answer on your own.

haha yeah, it’s called [rubber duck debugging](https://en.wikipedia.org/wiki/Rubber_duck_debugging)

> When you select one row or column, the matrix will get flattened, as this is numpy's behavior and often very practical.

Oh, once upon a time I made sure that this doesn’t happen in AnnData, since AnnData is always a 2D structure (You should always have (at least one) named cell(s) and gene(s), never just a 1D vector of expression values without knowing what dimension it is along)
