### ISSUE TITLE
No obsm slot after saving with adata.write_loom

### ISSUE THREAD

**Issue by Fougere87** [theislab/anndata#111]
Hi all and thank you a lot for your work,
I performed analysis of a big single set data set using scanpy and then producing pca, umap, draw_graph etc. I saved my adata object using adata.write_loom("myfile.loom") and when re opened these using adata =  sc.read_loom("myfile.loom"), I could not find any obsm field containing the different embeddings that were produced.. 
What I don't understand is that all other fields where present.

This data set is the merge of different loom files coming from velocyto script on bam files.

Is it normal that we cannot retrieve the obsm slot after writing the loom file ?

Thank you by advance !

**Comment by falexwolf** [comment]
The problem is that the `loom` file format doesn't support multi-dimensional annotations. We should output a warning, you're right... I added it here: https://github.com/theislab/anndata/commit/3e93ed702ff83eca59edc1f63a035ff93319ca12

A hackish manual workaround is adding the coordinates as one-dimensional annotations to `.obs`.
