### ISSUE TITLE
gzip and bzip2 compression support in read()

### ISSUE THREAD

**Issue by gokceneraslan** [theislab/anndata#21]
Hey,

Currently csv/tsv files with gzip or bzip2 compression are not supported, if I'm not mistaken. There is  an issue in DCA (https://github.com/theislab/dca/issues/7) about this, so I wanted to file a tracking issue here.

I was thinking about simply adding `gzip.open()` and `bzip2.open()` calls based on the file extension, just like other functions in the implementation, but there is also an option of using pandas for that because if we add compression support to anndata `read_text()` will start to converge `pandas.read_csv()`. 

So would it make sense to use `pandas.read_csv` for all text file reading functionality? It's already a dependency of anndata, so I don't see why not.

**Comment by falexwolf** [comment]
I didn't use `pandas.read_csv()` in the beginning because
- pandas was no dependency
- the function was not smart about figuring out whether column and row labels are present and couldn't deal with the standard format that the header has one column less than the body (one really shouldn't have to provide a parameter for this)
- it was slower than what we finally wrote
- it took a lot more memory
I still can't believe that the last two points are actually true... and maybe they aren't (anymore)...

So, switching fully to `pandas.read_csv` would require a few hacks... I guess it's easier to  prepend `gzip.open()` instead, but I'm open also the other solution.
