### ISSUE TITLE
adata.raw.obs_vector('geneA') vs adata[:, 'geneA'].raw.X

### ISSUE THREAD

**Issue by VolkerBergen** [theislab/anndata#251]
`adata.raw.obs_vector('geneA')` works as expected while `adata[:, 'geneA'].raw.X` returns the full sparse matrix. Intended?

**Comment by ivirshup** [comment]
I think so, thought it's a little weird to see it written.

The `var` axis of `adata.raw` is not aligned to `var` axis of its parent. This was originally so you could subset by highly variable genes, but keep the raw values for plotting and differential expression. This extends to any subset of `adata` since we can't promise that the set of `var_names` will be the same. `adata.raw[:, 'geneA'].X` may be more what you're looking for?

**Comment by VolkerBergen** [comment]
indeed, was too rushed.. It's `adata.raw[:, 'geneA'].X`, of course. Thanks!
