### ISSUE TITLE
var_names_make_unique fails on some indices

### ISSUE THREAD

**Issue by bkmartinjr** [theislab/anndata#344]
If I load a loom file with non-unique var names, and then call `var_names_make_unique()`, it appears to do nothing -- the var names are still non-unique.

if it is called _again_, it seems to work.

**update:** the "run twice" solution will not resolve the failure for all datasets.  See below for root cause discussion.

Example:
```
>>> adata = sc.read_loom('matrix.loom')
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
>>> adata.var.index.is_unique
False
>>> adata.var_names_make_unique()
>>> adata.var.index.is_unique
False
>>> adata.var_names_make_unique()
>>> adata.var.index.is_unique
True
```

**Comment by mweiden** [comment]
Hi 👋,

We've chased this down a bit further. The code is working as intended, appending a `join + str(counter[v])` to each duplicate entry. The issue is when you have names that will collide with the newly renamed vars or obs. Take the following example:

```
['SNORD113', 'SNORD113', 'SNORD113-1`, `SNORD113-1-1', `SNORD113-1-1-1`, ...]
```

running `.var_names_make_unique` once:

```
['SNORD113-1', 'SNORD113-2', 'SNORD113-1`, `SNORD113-1-1', `SNORD113-1-1-1`, ...]
```

This is not unique. Run it again:

```
['SNORD113-1-1', 'SNORD113-2', 'SNORD113-1-1`, `SNORD113-1-1', `SNORD113-1-1-1`, ...]
```

Still not unique.

Given the right sequence, this could be infinite.
