### ISSUE TITLE
changing md5sum of seemingly identical AnnDatas

### ISSUE THREAD

**Issue by LisaSikkema** [theislab/anndata#379]
Hi!

I noticed that the md5sum of my file changes when I store my AnnData from one jupyter notebook session to an .h5ad file, then close the jupyter session, start a new session, read in the written .h5ad file and write it to a new .h5ad file. Do you know why that is?

Thanks!

Best,
Lisa Sikkema

**Comment by ivirshup** [comment]
So, I just looked into this a bit, and it looks like [this is expected](https://stackoverflow.com/questions/16019656/hdf5-file-h5py-with-version-control-hash-changes-on-every-save) for `hdf5` files since they save timestamps from writing. There's some more discussion of this here: https://github.com/h5py/h5py/issues/225.

**Comment by LisaSikkema** [comment]
oh yes that explains it, thanks a lot!!
