### ISSUE TITLE
Subsetting mysteriously removes color keys in the parent object

### ISSUE THREAD

**Issue by gokceneraslan** [theislab/anndata#387]
Following code:

```python
import scanpy as sc

adata = sc.datasets.paul15()
sc.pp.pca(adata)
sc.pl.pca(adata, color='paul15_clusters')

print(adata.uns['paul15_clusters_colors'])
ad = adata[adata.obs['paul15_clusters'] == '1Ery']
print(adata.uns['paul15_clusters_colors'])
```

produces the output:

```
['#1f77b4', '#ff7f0e', '#279e68', '#d62728', '#aa40fc', '#8c564b', '#e377c2', '#b5bd61', '#17becf', '#aec7e8', '#ffbb78', '#98df8a', '#ff9896', '#c5b0d5', '#c49c94', '#f7b6d2', '#dbdb8d', '#9edae5', '#ad494a']
['#1f77b4']
```

However, it should print the same list twice, because why would subsetting meddle in color vector in the uns of the main object? 

PS: This is reproducible with anndata 0.7.2 and 0.7.3 but not with 0.7.1, so the regression must have been introduced between 0.7.1 and 0.7.2.

PS2: Using `ad = adata[adata.obs['paul15_clusters'] == '1Ery'].copy()` instead doesn't change the outcome.

Gokcen.

**Comment by ivirshup** [comment]
I think I see what's happening.

Originally, whenever a view was made all of uns was copied. This was because of how graphs were stored in uns, and us not having a way to lazily subset them. Now that graphs are stored in `obsp`, there is no need to copy `uns`, which gives us much faster subsetting.

The problem is that how we managed colors relies on this copying, as it modifies the `uns` of the view.

There are a few possible solutions:

* The subset gets a shallow copy of the original `_uns` dict, so it won't modify the parent
* Colors are stored in a dict of `{category: #color, ...}` so they don't need to be subset.

**Comment by gokceneraslan** [comment]
Former is more fitting for the spirit of the view and latter is more explicit. So I feel like we should do both, but latter requires more changes, I guess 😅

**Comment by ivirshup** [comment]
To me, the latter is ultimately a better solution since it splits the concepts of colors and the specifics of pandas categoricals. I also think it's easier to work with, (e.g. `adata.uns["celltype_colors"]["CD1c+"] = "red"`). It will take a lot more work to do though, and require changes in scanpy. I think we should go with the former for now.

I think this is the cause of https://github.com/theislab/scanpy/issues/1134

**Comment by LuckyMD** [comment]
Would the shallow copy not mean that changing the subset would also change the colour in the main object? If that's the case, then this sounds dangerous... and it doesn't match with the CoW principle.

**Comment by gokceneraslan** [comment]
That's a good point. If you do `subset_adata.uns['cat_colors'] = [...]` then parent will keep it's colors but, `subset_adata.uns['cat_colors'][0] = 'white'` would modify both the subset and the parent I think, right @ivirshup ?

**Comment by gokceneraslan** [comment]
https://github.com/theislab/scanpy/issues/1269 might be related

**Comment by ivirshup** [comment]
> `subset_adata.uns['cat_colors'][0] = 'white'` would modify both the subset and the parent I think

Yeah, that'll happen.

IIRC, I believe we haven't always made copies of `uns` for views, and only did it if we were going to modify something. This has a similar issue.

In general, I think this is a problem with the compatibility of python with copy on write semantics. We don't really have a way to ask if an arbitrary object will get modified. We could recursively make objects we recognize in `uns` into CoW views. However, array views have some weird behaviour and I'd like to avoid their usage until that's cleared up.

At the moment, my feeling is that we could leave it be until it causes an issue.

**Comment by gokceneraslan** [comment]
I agree with Malte, it's safer.

**Comment by ivirshup** [comment]
I don't think it's worth the cost of making a full copy of `uns` for each subset because people can store a lot there. We could make views have lazy copies of `uns`, so values do get copied – but only when the are first accessed.
