### ISSUE TITLE
Intuitive way to create new variables

### ISSUE THREAD

**Issue by mattmajo** [theislab/anndata#393]
Hi there, I am wondering if there is an easy way to access single variables in the anndata object. For example, what I am trying to do is create a new variable in my data matrix that is similar to the n_var variable. I intend for this new variable to be several other variables added together.
Is there a way to do this without diving into the .X dataframe?

**Comment by LuckyMD** [comment]
Hi @mattmajo,

You can quite easily create new variables by storing these in `adata.var`, by doing sth like this:
```
adata.var['new_var'] = ['This is var '+idx for idx in adata.var_names]
```

That variable is then retrievable via `adata.var['new_var']`. The same is possible with `adata.obs`. Indeed, `obs` and `var` are just pandas dataframes, and can be handled as such.

**Comment by mattmajo** [comment]
Okay, I have an anndata set with:

```
>>> adata.var_names
 Index(['TSPAN6', 'TNMD', 'DPM1', ....])
```

When I call:
``` 
adata.var['new_var'] = [x+y for x, y in zip(adata.var['TSPAN6'], adata.var['TNMD'])]
```
I receive `KeyError: 'TSPAN6'`

Any help would be appreciated.

**Comment by LuckyMD** [comment]
You can check what is stored in your `adata.var` by just looking at the output of `adata`. The expression values for individual genes are stored in `adata.X`. You can always access this via:
`adata[:,'TSPAN6'].X`.


If you want to work on the `adata.X` numpy ndarray it would be much faster to use numpy operations directly rather than iterate over two numpy arrays via a list comprehension. Also, it seems you are looking to add the expression of two genes across cells. So, you would need to store this in `adata.obs` (which is the same length as the observations/cells). So, this might be better:
```
adata = sc.datasets.pbmc68k_reduced()
adata.obs['add_two_genes'] = adata[:,['HES4','TNFRSF4']].X.sum(1)
```
