### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by ecerami** [theislab/anndata#490]
I am trying to load an 18GB h5ad file on Ubuntu.  (am currently using Linode w/ 2 GB RAM).

In reading the file, I am getting:

`numpy.core._exceptions.MemoryError: Unable to allocate 4.50 GiB for an array with shape (54313, 22216) and data type float32`

I am using the backed option, e.g.:

`self.adata = anndata.read_h5ad(file_name, backed="r")`

Are there additional options to read this file without loading everything into memory or do I just need more RAM?   Can you also explain what backed="r" actually does?

My use case is that I want to extract all annotations, but only a few genes.

Thanks for making anndata!

**Comment by ivirshup** [comment]
`backed` mode is pretty limited right now, only the `X` matrix is not loaded into memory. We are planning on making low memory access to the data more possible in the near future.

Do you have data in `layers`? That could be the issue here.

> My use case is that I want to extract all annotations, but only a few genes.

This particular use case should be viable soon. I can ping you once this is on master, if you'd like.

**Comment by ecerami** [comment]
Thanks for getting back to me.  I was able to address the issue by adding more memory.  But, if you can let me know regardig the future gene slice feature, that would be great.  Closing issue for now.
