### ISSUE TITLE
Codec for Saving Lists of Strings in Zarr

### ISSUE THREAD

**Issue by ilan-gold** [theislab/anndata#491]
I am trying to read zarr-stores that are the result of `write_zarr` in JavaScript, and the string parsing is rather haphazard right now - for example, this is the decoded output of the `obs` index:
```
G�������778����1409����3642����1302����…
``` 
While it is simple to parse out the `����` characters, it is less easy to tell that the `G` does not belong there (it does not).  This is a bit of a recurring issue and I'm wondering if the culprit is this: https://github.com/theislab/anndata/blob/99cbf45f19b0480ad18be51e5b919a9da0694fe3/anndata/_io/zarr.py#L158-L164
There is no `vlen-utf8` equivalent in JavaScript so I use the [`TextDecoder` API](https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder/encoding) which does `utf-8` decoding (and not that badly as the above is almost correct).  

However, I am wondering if there is a reason not to use the [JSON codec instead](https://numcodecs.readthedocs.io/en/stable/json.html#numcodecs.json.JSON)? Or perhaps it could be possible to use no codec at all given the small size of this part of the store?  I am going to experiment a little bit with this and can report back but wanted to get the ball rolling to see if you all knew anything about this, specifically if there is a use case for `vlen-utf8` outside of saving strings in AnnData (that is the only place I have seen it).

**Comment by ivirshup** [comment]
I'm not too familiar with how you would be accessing a zarr file from javascript. It seems to me like this is a bug or missing feature in the javascript implementation. Maybe a feature request should be opened for this on the [numcodecs.js repo](https://github.com/manzt/numcodecs.js)?

> However, I am wondering if there is a reason not to use the JSON codec instead? 

Mostly to avoid parsing, and keep reading and writing fast. I believe it's less straightforward to have partial access on a JSON array, since the simple implementation would be to parse the whole thing.

However, maybe this is something we could allow you to specify when writing your data?

**Comment by ilan-gold** [comment]
I had some time to look at this @ivirshup and it seems that it is an "issue" with numcodecs (python) in so far as the data is probably not meant to be used outside of that context.  They add a header to strings, which was causing issues (JSON compressor also seems to do the same, although I haven't been able to track down the source of this to confirm but have seen it when inspecting the outputs):

https://github.com/zarr-developers/numcodecs/blob/2c1aff98e965c3c4747d9881d8b8d4aad91adb3a/numcodecs/vlen.pyx#L34

Once this is removed in JavaScript, it seems like smooth sailing.  Thanks.  Closing this.
