### ISSUE TITLE
`uns` has same id on copied subset

### ISSUE THREAD

**Issue by VolkerBergen** [theislab/anndata#571]
The .uns items in a copy of anndata have the same id's as in the original anndata:
```
adata = sc.datasets.blobs()
adata.uns['info'] = {'numbers': '123'}
adata_copy = adata[:10].copy()

adata_copy.uns['info']['numbers'] = 'XX'
print(adata.uns['info']['numbers'])
```
returns 'XX' and gets overwritten even though it's modified on a copy.

In fact, id(adata_copy.uns) != id(adata.uns), while id(adata_copy.uns['cydata_pull']) == id(adata.uns['cydata_pull']).

Any thoughts?

**Comment by gokceneraslan** [comment]
Seems related to this https://github.com/theislab/anndata/issues/387#issuecomment-635067263 which was fixed 🤔

**Comment by VolkerBergen** [comment]
Thanks for linking @gokceneraslan. Yet I don't see how it was resolved. Modifying `.uns` of the parent (after copying a subset/view) is on the latest version from master. Is there a reason/rationale of not deepcopying `.uns` @ivirshup?

**Comment by ivirshup** [comment]
I think this is being caused by a lot of special casing around uns conflicting. We didn't `deepcopy` `uns` in `.copy` since that caused an error in a number of cases, so there was a bunch of work done to get around that. I've opened a PR where we do just `deepcopy` `.uns` since it should just be a dict.

**Comment by VolkerBergen** [comment]
I can confirm that it is resolved by your PR. Thanks @ivirshup.
