### ISSUE TITLE
Simpler, more consistent docstrings

### ISSUE THREAD

**Issue by falexwolf** [theislab/anndata#86]
I'd like to converge to simpler, more consistent docstrings, similar to the purely-markdown ones in Tensorflow.

- rendering type annotations in the same way as literals in the remaining docs: https://github.com/theislab/anndata/commit/bef1c35ae4adf9e5a342cdba3ec370cd14321a9c
- simplifying `Union[A, B]` to `A, B` by copying @flying-sheep's commit for resolving   https://github.com/theislab/scanpy/issues/379: https://github.com/theislab/anndata/commit/bef1c35ae4adf9e5a342cdba3ec370cd14321a9c
- enclosing single backticks are interpreted as literal text as in markdown and no longer as the rarely-useful `title-literal`: https://github.com/theislab/anndata/commit/f2c65e0afc529bc284bff6bcc20b75bf95700898
- format literals consistently across interpreted roles such as :class: and "ordinary" literals: https://github.com/theislab/anndata/commit/8f6bd391b68be264eb094ccd12a3becc221058d0
- consistent font size across type annotations and other literals: https://github.com/theislab/anndata/commit/b66566aba225b10576db638916112c668a174516
- do not show `Mapping` arguments in docstring, always hide `Optional` keyword, not only when preceding `Union`: https://github.com/theislab/anndata/commit/555cd5b2686b336ebd6df03399514e7215c177f8

**Comment by falexwolf** [comment]
This is the result for [AnnData](https://anndata.readthedocs.io/en/latest/anndata.AnnData.html#anndata.AnnData). Hope it's evident that it's much more simple and pleasing to look at...

If I did anything stupid, I'm happy to read about that: @flying-sheep @ivirshup

**Comment by flying-sheep** [comment]
Some issues:

- It’s impossible to see which types are links now:

    ![grafik](https://user-images.githubusercontent.com/291575/49723603-1b9a7480-fc5f-11e8-8557-99ddcdc552a1.png)

    here, `Mapping` is clickable, but the others aren’t, which leads to the next point:

- 555cd5b2686b336ebd6df03399514e7215c177f8 is a very misguided change, as hiding the key and value types of `Mapping`s actively makes the docs less informative and therefore worse. I reverted it in bbe1b5739b0bbd8fc4ee34ff3ffb8284d153fdc0.
- I hope you mean that `Optional[T]`s are replaced with `T, None` and not that the fact that you can specify `None` is hidden. However I see that in [the current master](https://github.com/theislab/anndata/blob/master/docs/conf.py#L230-L231) there is still code to render `Optional`…

We also should add ndarray and DataFrame to the `qualname_overrides`

**Comment by LuckyMD** [comment]
Quite a bit of effort is being put into making this nice and informative, which is great... but the informative descriptions are inevitably fairly technical as well. I don't want to side track this discussion, but just a quick note: it would really help if there was a beginner's guide documentation to using AnnData objects (slicing, etc.). I have found that new students often struggle learning scanpy from the documentation alone.

**Comment by flying-sheep** [comment]
That’s definitely a very good idea! We should do this!

However, you seem to imply that these changes add more technical detail to the docs while in reality, the docs *tried* to convey the same amount of technical details in a looser language. They are supposed to be there.

**Comment by falexwolf** [comment]
@flying-sheep: I don't agree with your four arguments above. And I'd be happy if you reverted your reversion of the commit. I'm back in Germany on Thursday and at the institute on Tuesday. We can also talk this through on a video call.

The fact that we just had a very long discussion concluding (regarding the subtopic "docstrings") with @ivirshup stating that he ["completely agreed on what makes a good docstring"](https://github.com/theislab/scanpy/issues/373#issuecomment-444715545) triggered that I moved forward to make the changes I described above without getting in another long discussion. It was clear that you would want to see the arguments of `Mapping` in the docs and that I wouldn't want them.

I'm stressing it again: I'm OK with type annotations in the code. But I really want simple docstrings that stick to the conventions of all the major packages. In addition to these considerations, the commit you reverted reintroduces inconsistencies: the `Optional` keyword sometimes got hidden and sometimes didn't... also, it is incompatible with the font styling of the literals as it introduces brackets, as we discussed several weeks ago.

@LuckyMD: I completely agree! There should be a tutorial! I'm just lacking the bandwidth to go into it.

**Comment by LuckyMD** [comment]
@falexwolf Haha... I believe you mentioned it before when I brought it up... I'm just going to keep bringing it up so it doesn't slip entirely off the agenda.

Also, while I understand the type annotations give more information... interactive help documentation in ipython (pressing `shift` + `tab` twice) becomes quite hard to read if you just quickly want to find the name of an argument in the function.

**Comment by falexwolf** [comment]
> I'm just going to keep bringing it up so it doesn't slip entirely off the agenda.

There will be a very basic tutorial at some point, guaranteed! And one that's not as awful as [this](https://falexwolf.de/blog/171223_AnnData_indexing_views_HDF5-backing/). Just right now, it's really difficult... Maybe this is something that could move up the list of priorities for @Koncopd, if he'd like to do something like this.

> Also, while I understand the type annotations give more information... interactive help documentation in ipython (pressing shift + tab twice) becomes quite hard to read if you just quickly want to find the name of an argument in the function.

So, I understand that you agree that hitting shift + tab twice becomes awfully hard to read when type annotations in the function headers are used and the docstrings themselves miss types and default values? That's what I've kept arguing for since @flying-sheep brought up type annotations for the first time in Scanpy/AnnData (6 months ago?). In essence, 99% of us are hackers who just use jupyter and shift + tab and learn everything by that. And even a hacker who really knows how to code and is making a great developer, like @ivirshup, agrees on that. @flying-sheep keeps arguing from a developer perspective who has a fully configured PyCharm and aims to build complex software from simpler blocks... I get what he says, but as I'm definitely on the hacker's side of things, learning everything using shift + tab, my top priority is simple, human-readable docstrings and an API that enables writing scripts that are as simple as possible and clearly don't fall in the category "software".

**Comment by falexwolf** [comment]
> Generally, it’s error prone to copy all the docs code between scanpy and anndata. we should create a little sphinx plugin that does all this for us and can be used in both projects.

Completely agree on this! :)

> Please don’t hide valuable information.

Agree on this. But I'd prefer to hide information of low relevance. In the example you copied above, it's completely irrelevant as it's redundant. The docstring says:

> Key-indexed one-dimensional observations annotation of length #observations.

And, hence, this bloated beast of a parameter definition
![image](https://user-images.githubusercontent.com/16916678/49844474-248b6300-fd91-11e8-952e-c8e6173c61d4.png)

is unacceptable. I've struggled with the look of it, for months, now (leave alone that font sizes and styles were inhomogeneous and it was much worse before Saturday...).

Acknowledging that there has already been an insanely long thread on type annotations, we might consider opening up a new repository "scanpy-playground" or something, where we can have all these sandpit fights (if this is a notion) 🙂 At this stage, I personally would have stopped watching the Scanpy repo, I guess.

**Comment by falexwolf** [comment]
PS: This is the inconsistent use of the `Optional` keyword:
![image](https://user-images.githubusercontent.com/16916678/49844907-9e701c00-fd92-11e8-80f6-9a0805f083d8.png)
All parameters here are optional, not only `uns`. But, yeah, I'd like to get rid of it completely, anyways... as in the changes above, where the same thing looked this way
![image](https://user-images.githubusercontent.com/16916678/49845005-e98a2f00-fd92-11e8-922f-462ba5419013.png)
The only thing that misses, here, in order to hold up to the convention of the major numerical python packages, is the default value...

**Comment by flying-sheep** [comment]
> It was clear that you would want to see the arguments of Mapping in the docs and that I wouldn't want them.

No, it was not clear that you’d want this, and I still can’t believe you’d actually want this.

There’s easily information about how things work that get passed automatically to the reader. You added a commit that artificially withholds that information, forcing readers to look into the code if the want it? I think I must misunderstand something here, that can’t be your intention.

I’m of course OK with presenting the information in another way, and leaving it out in cases of `Any` (e.g. `Mapping[Any, Any]` → `Mapping`), but not to withhold it.

> the Optional keyword sometimes got hidden and sometimes didn't...

As said: I also want consistency. I slightly prefer wrapping things into `Optional` instead of adding a `, None`, since `None` is not a type. `NoneType` is, but adding that to a list would be confusing.

> also, it is incompatible with the font styling of the literals as it introduces brackets, as we discussed several weeks ago.

Exactly, this is why we changed the font, which you since reverted. I think having a high density of types in a line means that the boxes around them look confusing. [Other docs](https://aiohttp.readthedocs.io/en/stable/client_quickstart.html#make-a-request) consistently *don’t* put their types into boxes, which is a route that I’d prefer to having boxes everywhere.

> interactive help documentation in ipython (pressing shift + tab twice) becomes quite hard to read if you just quickly want to find the name of an argument in the function.

You seem to have missed that I fixed this in ipython/ipython#11505:

![grafik](https://user-images.githubusercontent.com/291575/49578355-7707f200-f941-11e8-89e9-aa78ae023d8b.png)

One per line, *and* you know what you can pass in there as well! Combined with ipython/ipython#11506, autocompletion will work better since Jedi can suggest you the right objects based on their types thanks to type annotations!

> So, I understand that you agree that hitting shift + tab twice becomes awfully hard to read when type annotations in the function headers are used and the docstrings themselves miss types and default values? That's what I've kept arguing for since @flying-sheep brought up type annotations for the first time in Scanpy/AnnData (6 months ago?)

…but you *know* that I fixed this in IPython. Instead of saying “You can’t make this better because $tool can’t handle what you do”, why don’t we improve “$tool”? If they have a release every month, there’s enough time to do that and get in the improvements that $tool couldn’t handle within 2 months.

**Comment by flying-sheep** [comment]
> If you display the documentation as you do above, it is displayed nicely, but if you do it with shift + tab, then it's all in one line and in your example above the default for metric would be quite far away and make it difficult to read.

You got that wrong, both work the same. But the fix is in IPython 7.3, see below:

> But yes... I will update again in the new year and take a look at your pretty documentation ;).

I fixed it in IPython 7.3, not in scanpy. The problem was that IPython relied on `inspect.Signature.__str__` which isn’t designed for long signatures. So it had to be fixed in IPython or Python itself (which provides the `inspect` module).

I generally distinguish between introducing a problem and exposing one. When using a feature exposes a problem, too many people avoid using it, optnig for a different, subpar solution. If it’s not too impractical, I instead often use the badly-supported feature and file an issue in the project that really has the problem. (And if I have the time, I help them fix it) That way, everything gets better instead of remaining shit.

**Comment by flying-sheep** [comment]
I think we all have different approaches and views, and if we get together and discuss our wants and perspectives, we’ll end up with a better solution that any of us would individually.

I’m less practical than necessary, but I have the better vision of what’s feasible to implement technically. When we communicate, we can make something great, even if we don’t have all the time in the world. But we have to try. Let’s talk in person when you’re here @falexwolf :smiley:

**Comment by flying-sheep** [comment]
> Thanks also for your version of it in brief, which was more informative for me actually ;)

It’s all in the table here: https://docs.python.org/3/library/collections.abc.html#collections-abstract-base-classes

> A lot of people using scanpy are biologists who may not understand the concept of an iterator or a container. And they may move from scanpy if they feel they are required to understand the basic workings of python to use scanpy.

Good point! A balance has to be struck, and I have one requirement:

Diving into the code to find out what *exactly* I can pass to a function is bullshit and should never happen. The information in the official docs needs to be *complete* and *unambiguous*. The way it will look is up for debate. We can implement everything, including pop-ups and other interactive bling. But I veto that we completely get rid of information.

I went for type annotations, because they’re a standard, unambiguous, and complete way to represent everything. I’m open for suggestions.

**Comment by falexwolf** [comment]
Hey! Thank you for both your contributions @LuckyMD and @flying-sheep! @LuckyMD makes exactly the points that worry me.

Let's continue the discussion in person.

I just want to apologize that I didn't mention the IPython fix above, @flying-sheep. I myself had forgotten to update my IPython and hence was still staring at the old help outputs and arguing from the look of it...  I don't know why I didn't make the connection with our previous discussion when writing the stuff above.  🙈

**Comment by flying-sheep** [comment]
No worries, you have a lot on your mind! I’m sorry if I sounded too rude in my last messages here, I wasn’t in a good place last week. All better now!

**Comment by LuckyMD** [comment]
@flying-sheep Sorry... I somehow missed your last post. I actually agree with pretty much everything you wrote before. And I am in the easier position that I'm just pointing out difficulties rather than suggesting improvements. To try and contribute a bit more constructively: Maybe it's possible to separate the complete and unambiguous info from the general documentation? Like having an easy to read documentation and a detailed, technical documentation? That could be quite a bit of work though... Can you put two function headers in readthedocs?

Either way.. I'm sure you guys will come to a good solution offline tbh. The way scanpy is shaping up so far definitely warrants that trust!

**Comment by flying-sheep** [comment]
Go for it! it’s a quick change now.

**Comment by flying-sheep** [comment]
This is fixed! yay!
